### ISSUE TITLE
Connection Failed 

### ISSUE THREAD

**Issue by ghost** [pokurt/Chat-Bot-ENG#4]
Logs :-  https://del.dog/sirfahigno.txt

**Comment by rebizzz** [comment]
The domain endpoint.mannu.me is no longer available @pokurt is no longer maintaining it

**Comment by CustomIcon** [comment]
@bhardwajjEE @reejit 
the source for the server is open 🎉 
here is the [link](https://github.com/OpenRestfulAPI/Chatterbot-API) if you guys wondering.

**Comment by ghost** [comment]
Ah .. Thank you both @reejit & @pokurt  😀
